### PR TITLE
Update features.md to reflect minimum SIMD requirements

### PR DESCRIPTION
**Pull request by CKingX**
* Updated macOS minimum SIMD support from SSSE3 to SSE4.1 as macOS Sierra and later require Penryn
* Included the minimum SIMD support for most Windows targets of SSE3

### CODE REVIEW

**Comment by CKingX** [comment]
I don't think the tests are failing due to the change as I only updated the features page of the performance guide.

**Comment by workingjubilee** [comment]
Oh yes, several fundamental ideas that this crate hinges on got rewritten.

**Comment by workingjubilee** [comment]
@CKingX I have no intention of merging your change, sorry! This documentation should go to the rust-lang/rust repository, for the platform support pages hereish: https://github.com/rust-lang/rust/tree/master/src/doc/rustc/src

**Comment by CKingX** [comment]
So I looked into the platform support and it doesn't make sense to put it in there. I also don't think constantly updating features.md whenever a target changes makes sense. Would it make sense to create a new PR explaining that you can look up the default target features with `rustc --print cfg` or for other targets, `rustc --print cfg --target={target}`?

**Comment by workingjubilee** [comment]
Not even in the docs for the targets? https://github.com/rust-lang/rust/tree/master/src/doc/rustc/src/platform-support

And sure...?

**Comment by CKingX** [comment]
Thanks! I will look into updating those docs.

**Comment by CKingX** [comment]
It seems a lot of the docs on the targets list if things like SSE are disabled. Would it make sense updating the Windows 7 target arch to list it only supports SSE2 by default unlike the regular targets?

Also thank you for your help!

**Pull request closed without merging**
