### PR TITLE
Account some warnings to fix CI

### LINKED ISSUE #5: min_element / max_element produce incorrect results for NaNs in the last place
See it live: https://play.rust-lang.org/?gist=2ccd8fb4e41fc1b28a1cc6a2e5774a7b&version=nightly

```rust
#![feature(repr_simd)]
#![feature(platform_intrinsics)]

extern "platform-intrinsic" {
    fn simd_reduce_min<T,U>(a: T) -> U;
}

#[repr(simd)]
pub struct F(f32, f32);

pub fn foo(x: F) -> f32 {
   unsafe { simd_reduce_min(x) }
}

fn main() {
 let x = F(1.0, -1.0);
 assert_eq!(foo(x), -1.0);   // OK
 let y = F(std::f32::NAN, -1.0);
 assert_eq!(foo(y), -1.0);   // OK
 let z = F(-1.0, std::f32::NAN);
 assert_eq!(foo(z), -1.0);  // FAILS: returns NaN
}
```

---

So I've filled: https://bugs.llvm.org/show_bug.cgi?id=36982 

This issue is probably because `llvm.vector.reduce.fmin/fmax` have the semantics of `fcmp` instead of `minnum`/`maxnum`. We will probably need to workaround this issue in `stdsimd`. 

What we want is the same semantics that Rust specifies for `min`/`max` on floating-point primitive types. For `min` this is:

> Returns the minimum of the two numbers. If one of the arguments is NaN, then the other argument is returned.

This looks compatible with the specifications of IEEE754-2018 (drafts are here: http://754r.ucbtest.org/drafts/). From the latest draft (P754-233 17-Mar-2018):

```
**minimumNumber**(x, y) is x if x<y, y if y<x, and the number if one operand is a number and the
other is a NaN. For this operation, −0 compares less than +0. If x=y and signs are the same it is
either x or y. If both operands are NaNs, a quiet NaN is returned, according to 6.2. If either
operand is a signaling NaN, an invalid operation exception is signaled, but unless both operands
are NaNs, the signaling NaN is otherwise ignored and not converted to a quiet NaN as stated in
6.2 for other operations.

**maximumNumber**(x, y) is x if x>y, y if y>x, and the number if one operand is a number and the
other is a NaN. For this operation, +0 compares greater than −0. If x=y and signs are the same it
is either x or y.If both operands are NaNs, a quiet NaN is returned, according to 6.2. If either
operand is a signaling NaN, an invalid operation exception is signaled, but unless both operands
are NaNs, the signaling NaN is otherwise ignored and not converted to a quiet NaN as stated in
6.2 for other operations
```

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #5

### CODE REVIEW

**Review by Lokathor — APPROVED** [review]

**Comment by Lokathor** [comment]
Looks like CI is less than fully fixed :/

**Comment by JohnTitor** [comment]
Ouch, checking now...

**Comment by JohnTitor** [comment]
Failures:
```
---- v128::i8x16_ops_scalar_shifts::ops_scalar_shifts stdout ----

thread 'v128::i8x16_ops_scalar_shifts::ops_scalar_shifts' panicked at 'assertion failed: `(left == right)`

  left: `i8x16(1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0)`,

 right: `i8x16(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`', src/v128.rs:6:1

---- v128::i8x16_ops_vector_rotate::rotate_ops stdout ----

thread 'v128::i8x16_ops_vector_rotate::rotate_ops' panicked at 'assertion failed: `(left == right)`

  left: `i8x16(1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0)`,

 right: `i8x16(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`', src/v128.rs:6:1

---- v128::i8x16_ops_vector_shifts::ops_vector_shifts stdout ----

thread 'v128::i8x16_ops_vector_shifts::ops_vector_shifts' panicked at 'assertion failed: `(left == right)`

  left: `i8x16(1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0)`,

 right: `i8x16(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`', src/v128.rs:6:1

---- v128::u8x16_ops_scalar_shifts::ops_scalar_shifts stdout ----

thread 'v128::u8x16_ops_scalar_shifts::ops_scalar_shifts' panicked at 'assertion failed: `(left == right)`

  left: `u8x16(1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0)`,

 right: `u8x16(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`', src/v128.rs:11:1

---- v128::u8x16_ops_vector_rotate::rotate_ops stdout ----

thread 'v128::u8x16_ops_vector_rotate::rotate_ops' panicked at 'assertion failed: `(left == right)`

  left: `u8x16(1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0)`,

 right: `u8x16(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`', src/v128.rs:11:1

---- v128::u8x16_ops_vector_shifts::ops_vector_shifts stdout ----

thread 'v128::u8x16_ops_vector_shifts::ops_vector_shifts' panicked at 'assertion failed: `(left == right)`

  left: `u8x16(1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0)`,

 right: `u8x16(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`', src/v128.rs:11:1

failures:

    v128::i8x16_ops_scalar_shifts::ops_scalar_shifts

    v128::i8x16_ops_vector_rotate::rotate_ops

    v128::i8x16_ops_vector_shifts::ops_vector_shifts

    v128::u8x16_ops_scalar_shifts::ops_scalar_shifts

    v128::u8x16_ops_vector_rotate::rotate_ops

    v128::u8x16_ops_vector_shifts::ops_vector_shifts

test result: FAILED. 2544 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.26s
```

So something goes wrong on AArch64 since CI passed, maybe related to the recent LLVM bumps? I don't see any related commits here. I'd like to file this as an issue and skip tests for now if it's reasonable. @Lokathor Thoughts?

**Comment by workingjubilee** [comment]
We've uncovered aarch64 optimization-related LLVM bugs in https://github.com/rust-lang/stdsimd/pull/80 so I would agree: it seems that something in aarch64 codegen is busted (maybe always, maybe only now) and it's likely not our fault. But the thought of shrugging off what appears to be a new behavioral deviation for tier 1 targets makes me itch.

**Comment by JohnTitor** [comment]
> But the thought of shrugging off what appears to be a new behavioral deviation for tier 1 targets makes me itch.

But on the other hand, this also hinders further tests on CI (https://travis-ci.com/github/rust-lang/packed_simd/builds/220445170).
I totally agree we shouldn't ignore this issue but... I'm not sure the fix here is straightforward.

**Comment by workingjubilee** [comment]
Well, this is blocking landing any other maintenance, so might as well I guess.

**Comment by Lokathor** [comment]
Looking at the changes, it's just tests changing right? So the code itself is no worse with this PR, it's only as broken as it might have been before. If we want to merge this we should and then we can continue later once the llvm bug is addressed.

**Comment by JohnTitor** [comment]
Okay, CI still has a lot of failures but at least we pass all the non-allow-failure jobs. I'm going to fix some of them but meanwhile, we can merge this to unblock other PRs?

**Pull request merged**
