### PR TITLE
Fix Clippy lints

### PR DESCRIPTION
**Pull request by GabrielMajeri**
This PR attempts to get CI to work again by fixing Clippy lints.

### CODE REVIEW

**Comment by GabrielMajeri** [comment]
It seems it still doesn't build currently because of the core_simd dependency

**Comment by gnzlbg** [comment]
I see :/

**Comment by mati865** [comment]
Core_arch was [fixed recently](https://github.com/rust-lang/stdarch/pull/824) but there is no new version yet, you could try patching Cargo.toml to use git version.

**Comment by GabrielMajeri** [comment]
Well this is just lovely. While trying to still fix the build I managed to get an ICE...
```
error: internal compiler error: src/librustc_mir/transform/qualify_consts.rs:1145: promotion candidate validation mismatches (see above)
```
I think it's going to take a while until we get CI working again...

**Comment by mati865** [comment]
There are no reports of this ICE in Rust repo. Can you temporary add `RUST_BACKTRACE=1` to the CI job and report it upstream?

**Comment by ecstatic-morse** [comment]
@GabrielMajeri rust-lang/rust#66016 should be fixed in the next nightly release. Thanks for reporting this BTW.

**Comment by mati865** [comment]
Clippy is green now, probably `core_arch` needs new release.

**Comment by workingjubilee** [comment]
This looks lovely! I know you wanted to fix CI with this but this looks like it fixes everything that is still blocking #292 so I'm going to merge it.

**Pull request merged**
