### PR TITLE
Remove reference to unused llvm_asm feature (no longer available on Rust nightly)

### LINKED ISSUE #340: Replace `llvm_asm!` with `asm!`
Since rust removed `llvm_asm!`: https://github.com/rust-lang/rust/commit/a34c0797528172ede89480e3033f7a5e71ea4735

https://github.com/rust-lang/packed_simd/blob/b47552659401299a2023e7f408316bfe2dd4476d/src/lib.rs#L227

### PR DESCRIPTION
**Pull request by hkratz**
Fixes #340.

### CODE REVIEW

**Comment by alamb** [comment]
Also fixes https://github.com/rust-lang/rust/issues/93025

**Comment by alamb** [comment]
cc @workingjubilee  (or anyone else who can merge this PR / publish a fix) 🙏

**Comment by workingjubilee** [comment]
Thank you! I will cut a release shortly.

**Comment by alamb** [comment]
Thank. you @hkratz  and @workingjubilee

**Pull request merged**
